### ISSUE TITLE
Installation with composer fails

### ISSUE THREAD

**Issue by spekulatius** [arillo/silverstripe-gulp-plate#4]
Installation using composer fails because the package isn't registered on packagist.org 

Is there a chance you could add it?

**Comment by nicolas-cusan** [comment]
The package is intended as a boilerplate/starting-point to develop your theme. Adding it to composer makes little sense as you will not want to update it once you start changing stuff.

I realise this ist not well reflected in the Readme, i will update it with better instructions on how to use and remove the composer.json (was just a test) to avoid confusion.
