### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by silverstripesk** [arillo/silverstripe-gulp-plate#5]
Hello,

your docs for silverstripe gulp plate are missing now, is any reason for it, please?

Best regards

Pali

**Comment by nicolas-cusan** [comment]
Hi @silverstripesk, we deleted the documentation repo because the docs where really outdated. Please refer to the Readme for basic documentation. I hope to find the time to write a better documentation soon.

**Comment by silverstripesk** [comment]
Hi Nicolas,

is it possible to send me old version (which is pretty fine for me) on my e-mail?

Thanks in advance.

Pali

Dňa 13. januára 2017 16:21:35 SEČ používateľ Nicolas Cusan <notifications@github.com> napísal:
>Hi @silverstripesk, we deleted the documentation repo because the docs
>where really outdated. Please refer to the Readme for basic
>documentation. I hope to find the time to write a better documentation
>soon.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/arillo/silverstripe-gulp-plate/issues/5#issuecomment-272468301

-- 
Odoslané z môjho Android zariadenia pomocou K-9 Mail.

**Comment by nicolas-cusan** [comment]
Hey Pali,

sorry for the late reply. Here is a zip: [gulp-plate-docs.zip](https://github.com/arillo/silverstripe-gulp-plate/files/721004/gulp-plate-docs.zip)

Best regards,
Nicolas

**Comment by silverstripesk** [comment]
Thanks!
